load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "kruskal",
    srcs = ["Kruskal.cpp"],
    hdrs = ["Kruskal.hpp"],
    deps = ["//UnionFind:union_find"], 
    visibility = ["//visibility:public"],
)
