load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "boruvka",
    srcs = ["boruvka.cpp"],
    hdrs = ["boruvka.hpp"],
    deps = ["//union_find:union_find"],
    visibility = ["//visibility:public"],
)
