load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "boruvka",
    srcs = ["Boruvka.cpp"],
    hdrs = ["Boruvka.hpp"],
    deps = ["//UnionFind:union_find"],
    visibility = ["//visibility:public"],
)
