load("@rules_cc//cc:defs.bzl", "cc_library", "cc_test")

cc_library(
    name = "boruvka",
    srcs = ["boruvka.cpp"],
    hdrs = ["boruvka.hpp"],
    copts = [
        "-std=c++17",
    ], 
    visibility = ["//visibility:public"],
)
