load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "lca",
    srcs = ["lca.cpp"],
    hdrs = ["lca.hpp"],
    copts = [
        "-std=c++17",
    ],
    visibility = ["//visibility:public"],
)
