load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "prim",
    srcs = ["prim.cpp"],
    hdrs = ["prim.hpp"],
    copts = [
        "-std=c++17",
    ],
    visibility = ["//visibility:public"],
)
